### ISSUE TITLE
Plugin support

### ISSUE THREAD

**Issue by ynishi** [ynishi/craffiti#8]
Make to execute command plugin.

**Comment by ynishi** [comment]
sample:

yaml minimum
```
# react.yaml

init: npx create-react-app {projectName} --template typescript
```
yaml standard
```
# react.yaml

name: react
init:
- npx create-react-app {projectName} --template typescript
install:
- npm install {projectName}
check:
- {init} && {install}
files:
  - name: file1.txt
    path: data
    content: |-
      abc
      def
  - name: file2.txt
    path: tmp
    content: |-
      ghi
```
same with Toml
```
# react.toml

name = "react"
cmd = ""
init = "npx create-react-app {projectName} --template typescript"
install = "npm install {projectName}"
[[files]]
path = "hw.tsx"
content = """
...
"""
```
